on: push

jobs:
  build:
    runs-on: windows-latest
    env:
      NugetApiKey: ${{ secrets.NugetApiKey }}
      

    steps:
      - uses: actions/checkout@v2
      
      - name: Build Module
        run: .\build.ps1 -CopyTemplate
        shell: powershell

      - name: Build DWG Trueview Package
        run: .\build.ps1 -GeneratePackage
        shell: powershell