on: push

jobs:
  build:
    runs-on: self-hosted
    env:
      NugetApiKey: ${{ secrets.NugetApiKey }}
      RepositoryUrl: ${{ secrets.REPOSITORYURL}}
      

    steps:
      - uses: actions/checkout@v2
      
      - name: Create Template
        run: .\build.ps1 -CopyTemplate
        shell: powershell

      - name: Build DWG Trueview Package
        run: .\build.ps1 -GeneratePackage -SuppressChocoOutput -Verbose
        shell: powershell

      - name: Publish DWG Trueview Package
        run: .\build.ps1 -PublishPackage
        shell: powershell